### ! get a users
GET http://localhost:5000/users

### get a users by id
GET http://localhost:5000/users/1

### update a user
patch http://localhost:5000/users/1
Content-Type: application/json

{
    "fullname": "adsf",
    "password": "asdf"
}

### delete a users by id
delete http://localhost:5000/users/24

### ! Auth

### register
POST http://localhost:5000/users/
Content-Type: application/json

{
    "fullname": "Muhammad Dwi Susanto",
    "email": "dwi@gmail.com",
    "password": "dwi"
}

### login
POST http://localhost:5000/login/
Content-Type: application/json

{
    "email": "dwi@gmail.com",
    "password": "dwi"
}

### ! get a category
GET http://localhost:5000/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImZ1bGxuYW1lIjoiTXVoYW1tYWQgRHdpIFN1c2FudG8iLCJlbWFpbCI6ImR3aUBnbWFpbC5jb20iLCJpYXQiOjE2NjgwOTI1NDgsImV4cCI6MTY2ODA5MjYwOH0.dNsHVNnKhlvLrqp6rNNFQ8zXcplvrZtFUTrIem7ImPI

### get a category by id
GET http://localhost:5000/categories/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImZ1bGxuYW1lIjoiTXVoYW1tYWQgRHdpIFN1c2FudG8iLCJlbWFpbCI6ImR3aUBnbWFpbC5jb20iLCJpYXQiOjE2NjgwOTI1NDgsImV4cCI6MTY2ODA5MjYwOH0.dNsHVNnKhlvLrqp6rNNFQ8zXcplvrZtFUTrIem7ImPI

### create a category
POST http://localhost:5000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImZ1bGxuYW1lIjoiTXVoYW1tYWQgRHdpIFN1c2FudG8iLCJlbWFpbCI6ImR3aUBnbWFpbC5jb20iLCJpYXQiOjE2NjgwODIxMzAsImV4cCI6MTY2ODA4MjE5MH0.MFyLPFUMBzUj7F8VSfNmNQto2mXhAhx_KfEHD-m7Gdg

{
    "name": "asdf"
}

### update a category
patch http://localhost:5000/categories/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImZ1bGxuYW1lIjoiTXVoYW1tYWQgRHdpIFN1c2FudG8iLCJlbWFpbCI6ImR3aUBnbWFpbC5jb20iLCJpYXQiOjE2NjgwODIxMzAsImV4cCI6MTY2ODA4MjE5MH0.MFyLPFUMBzUj7F8VSfNmNQto2mXhAhx_KfEHD-m7Gdg

{
    "name": "kendaraan"
}

### delete a category
delete http://localhost:5000/categories/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImZ1bGxuYW1lIjoiTXVoYW1tYWQgRHdpIFN1c2FudG8iLCJlbWFpbCI6ImR3aUBnbWFpbC5jb20iLCJpYXQiOjE2NjgwODIxMzAsImV4cCI6MTY2ODA4MjE5MH0.MFyLPFUMBzUj7F8VSfNmNQto2mXhAhx_KfEHD-m7Gdg

### ! get a todolist
GET http://localhost:5000/todolists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImZ1bGxuYW1lIjoiTXVoYW1tYWQgRHdpIFN1c2FudG8iLCJlbWFpbCI6ImR3aUBnbWFpbC5jb20iLCJpYXQiOjE2NjgwOTI1NDgsImV4cCI6MTY2ODA5MjYwOH0.dNsHVNnKhlvLrqp6rNNFQ8zXcplvrZtFUTrIem7ImPI

### get a todolist by id
GET http://localhost:5000/todolists/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImZ1bGxuYW1lIjoiTXVoYW1tYWQgRHdpIFN1c2FudG8iLCJlbWFpbCI6ImR3aUBnbWFpbC5jb20iLCJpYXQiOjE2NjgwODIxMzAsImV4cCI6MTY2ODA4MjE5MH0.MFyLPFUMBzUj7F8VSfNmNQto2mXhAhx_KfEHD-m7Gdg


### create a todolist
POST http://localhost:5000/todolists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImZ1bGxuYW1lIjoiTXVoYW1tYWQgRHdpIFN1c2FudG8iLCJlbWFpbCI6ImR3aUBnbWFpbC5jb20iLCJpYXQiOjE2NjgwODIxMzAsImV4cCI6MTY2ODA4MjE5MH0.MFyLPFUMBzUj7F8VSfNmNQto2mXhAhx_KfEHD-m7Gdg

{
    "title": "coba title",
    "description": "coba description",
    "status": "To Do",
    "userId": "14",
    "categoryId": "1"
}

### update a todolist
PATCH http://localhost:5000/todolists/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImZ1bGxuYW1lIjoiTXVoYW1tYWQgRHdpIFN1c2FudG8iLCJlbWFpbCI6ImR3aUBnbWFpbC5jb20iLCJpYXQiOjE2NjgwODIxMzAsImV4cCI6MTY2ODA4MjE5MH0.MFyLPFUMBzUj7F8VSfNmNQto2mXhAhx_KfEHD-m7Gdg

{
    "title": "update title",
    "description": "update description",
    "status": "Doidng",
    "userId": "1",
    "categoryId": "1"
}

### Delete a todolist
DELETE http://localhost:5000/todolists/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImZ1bGxuYW1lIjoiTXVoYW1tYWQgRHdpIFN1c2FudG8iLCJlbWFpbCI6ImR3aUBnbWFpbC5jb20iLCJpYXQiOjE2NjgwODIxMzAsImV4cCI6MTY2ODA4MjE5MH0.MFyLPFUMBzUj7F8VSfNmNQto2mXhAhx_KfEHD-m7Gdg